spring:
  datasource:
    url: jdbc:mysql://localhost:3306/investsys?useSSL=false
    username: root
    password: root123


#mvc:
#  pathmatch:
#    matching-strategy:ANT_PATH_MATCHER

  jpa.hibernate.ddl_auto: update
